#pragma once
enum class TextureID {
  iconBook,
  iconSword,
  iconShield,
  iconCards,
  iconExit,
  bg2,
  clickedButton1,
  restButton,
  clickedButton,
  titleLogo,
  titleLogo1, 
  quote ,
  manorMap,
  bgDracula ,
  bgSherlock , 
  sherlockButtonNormal ,
  sherlockButtonHovered , 
  draculaButtonNormal,
  draculaButtonHovered ,
  bgInvisibleMan ,
  invisibleManButtonNormal ,
  invisibleManButtonHovered ,
  titleHeroSelection , 
  frame,

  baskervilleManorMap,

  // Dracula card art (assets/images/Dracula/cards/*.png)
  draculaAmbush,
  draculaBaptismOfBlood,
  draculaBeastform,
  draculaDash,
  draculaDoMyBidding,
  draculaExploit,
  draculaFeedingFrenzy,
  draculaFeint,
  draculaLookIntoMyEyes,
  draculaMistform,
  draculaPreyUpon,
  draculaRaveningSeduction,
  draculaThirstForSustenance,

  // Sherlock Holmes card art (assets/images/SherlockHolms/cards/*.png)
  sherlockHolmsAdministerAid,
  sherlockHolmsConfirmSuspicion,
  sherlockHolmsCounterPunch,
  sherlockHolmsDeduceStrategy,
  sherlockHolmsEducationNeverEnds,
  sherlockHolmsElementary,
  sherlockHolmsEliminateTheImpossible,
  sherlockHolmsFeint,
  sherlockHolmsFixedPointInAChangingAge,
  sherlockHolmsMasterOfDisguise,
  sherlockHolmsServiceRevolver,
  sherlockHolmsStudyMethods,
  sherlockHolmsTheGameIsAfoot,

  // Invisible Man card art (assets/images/InvisibleMan/cards/*.png)
  invisibleManCodedNotes,
  invisibleManConfound,
  invisibleManCovertPreparation,
  invisibleManDreamingOfRevenge,
  invisibleManEmergeFromMist,
  invisibleManImpossibleToSee,
  invisibleManIntoThinAir,
  invisibleManLurking,
  invisibleManReignOfTerror,
  invisibleManRollingFog,
  invisibleManSlipAway,
  invisibleManStepLightly,
  invisibleManVanish
};